name: data_class_gen
description: A sample command-line application.
version: 0.0.1
executables:
  data_class_gen:
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.0.0

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0
  analyzer: ">=7.0.0"
  collection: ">=1.17.0"
  path: ">=1.7.0"
  args:
  data_class_annotation:
    path: "annotation"

dev_dependencies:
  lints: ^5.0.0
  test: ^1.25.15

